// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DesiredStateRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Username             []string `protobuf:"bytes,2,rep,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesiredStateRequest) Reset()         { *m = DesiredStateRequest{} }
func (m *DesiredStateRequest) String() string { return proto.CompactTextString(m) }
func (*DesiredStateRequest) ProtoMessage()    {}
func (*DesiredStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *DesiredStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateRequest.Unmarshal(m, b)
}
func (m *DesiredStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateRequest.Marshal(b, m, deterministic)
}
func (m *DesiredStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateRequest.Merge(m, src)
}
func (m *DesiredStateRequest) XXX_Size() int {
	return xxx_messageInfo_DesiredStateRequest.Size(m)
}
func (m *DesiredStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateRequest proto.InternalMessageInfo

func (m *DesiredStateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DesiredStateRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Account struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Creds                string   `protobuf:"bytes,2,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Account) GetCreds() string {
	if m != nil {
		return m.Creds
	}
	return ""
}

type DesiredStateResponse struct {
	Accounts             *Account       `protobuf:"bytes,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Creds                []*Credentials `protobuf:"bytes,2,rep,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DesiredStateResponse) Reset()         { *m = DesiredStateResponse{} }
func (m *DesiredStateResponse) String() string { return proto.CompactTextString(m) }
func (*DesiredStateResponse) ProtoMessage()    {}
func (*DesiredStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *DesiredStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateResponse.Unmarshal(m, b)
}
func (m *DesiredStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateResponse.Marshal(b, m, deterministic)
}
func (m *DesiredStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateResponse.Merge(m, src)
}
func (m *DesiredStateResponse) XXX_Size() int {
	return xxx_messageInfo_DesiredStateResponse.Size(m)
}
func (m *DesiredStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateResponse proto.InternalMessageInfo

func (m *DesiredStateResponse) GetAccounts() *Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *DesiredStateResponse) GetCreds() []*Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type DeleteAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DesiredStateRequest)(nil), "v1alpha1.DesiredStateRequest")
	proto.RegisterType((*Credentials)(nil), "v1alpha1.Credentials")
	proto.RegisterType((*Account)(nil), "v1alpha1.Account")
	proto.RegisterType((*DesiredStateResponse)(nil), "v1alpha1.DesiredStateResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "v1alpha1.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "v1alpha1.DeleteAccountResponse")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x0d, 0x6d, 0xb4, 0x74, 0xa0, 0x07, 0xd7, 0x36, 0x12, 0x12, 0xb5, 0xe1, 0x44, 0x62, 0x24,
	0x16, 0x4f, 0xc6, 0x93, 0x56, 0x4f, 0xc6, 0xc4, 0xd0, 0x9b, 0xb7, 0x15, 0x46, 0x25, 0x41, 0x16,
	0x77, 0x97, 0xfa, 0xb7, 0xfc, 0x89, 0xa6, 0xb0, 0x0b, 0x45, 0x25, 0x3d, 0xbe, 0xcc, 0xfb, 0x98,
	0x37, 0xbb, 0x60, 0xc7, 0x2c, 0x7f, 0x4d, 0xdf, 0x82, 0x82, 0x33, 0xc9, 0x88, 0xb9, 0x5e, 0xd0,
	0xac, 0x78, 0xa7, 0x0b, 0xef, 0x01, 0x0e, 0xef, 0x50, 0xa4, 0x1c, 0x93, 0x95, 0xa4, 0x12, 0x23,
	0xfc, 0x2c, 0x51, 0x48, 0xe2, 0xc0, 0x88, 0xc6, 0x31, 0x2b, 0x73, 0xe9, 0x18, 0x73, 0xc3, 0x1f,
	0x47, 0x1a, 0x12, 0x17, 0xcc, 0x52, 0x20, 0xcf, 0xe9, 0x07, 0x3a, 0x83, 0xf9, 0xd0, 0x1f, 0x47,
	0x0d, 0xf6, 0xee, 0xc1, 0x5a, 0x72, 0x4c, 0x30, 0x97, 0x29, 0xcd, 0x44, 0x87, 0x5a, 0xbb, 0x34,
	0x78, 0x33, 0x2b, 0xa8, 0x10, 0x5f, 0x8c, 0x27, 0xce, 0xa0, 0x9e, 0x69, 0xec, 0x5d, 0xc1, 0xe8,
	0x46, 0xa5, 0xf5, 0xef, 0x31, 0x85, 0xbd, 0x98, 0x63, 0x22, 0x94, 0xba, 0x06, 0x1e, 0x87, 0x69,
	0xb7, 0x8e, 0x28, 0x58, 0x2e, 0x90, 0x9c, 0x83, 0xa9, 0x84, 0xa2, 0x32, 0xb2, 0xc2, 0x83, 0x40,
	0xdf, 0x20, 0x50, 0x61, 0x51, 0x43, 0x21, 0x67, 0xad, 0xf9, 0xd0, 0xb7, 0xc2, 0x59, 0xcb, 0xdd,
	0xea, 0xa7, 0x33, 0x2f, 0x36, 0x99, 0x19, 0x4a, 0xd4, 0x3e, 0xbb, 0x6e, 0xe8, 0x1d, 0xc1, 0xec,
	0x97, 0xa2, 0x5e, 0x33, 0xfc, 0x36, 0x60, 0xb2, 0xac, 0x1e, 0x6a, 0x85, 0x7c, 0x9d, 0xc6, 0x48,
	0x1e, 0xc1, 0xde, 0x2e, 0x44, 0x8e, 0xdb, 0x55, 0xfe, 0x79, 0x37, 0xf7, 0xa4, 0x6f, 0xac, 0xee,
	0xf0, 0x04, 0x93, 0x4e, 0x32, 0xe9, 0x08, 0xfe, 0x96, 0x70, 0x4f, 0x7b, 0xe7, 0xb5, 0xe3, 0xad,
	0xfd, 0x0c, 0xc1, 0xb5, 0xe6, 0xbc, 0xec, 0x57, 0xff, 0xeb, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0x45, 0x06, 0xff, 0x6f, 0x02, 0x00, 0x00,
}
