// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DesiredStateRequest struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Username             []string `protobuf:"bytes,2,rep,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesiredStateRequest) Reset()         { *m = DesiredStateRequest{} }
func (m *DesiredStateRequest) String() string { return proto.CompactTextString(m) }
func (*DesiredStateRequest) ProtoMessage()    {}
func (*DesiredStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *DesiredStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateRequest.Unmarshal(m, b)
}
func (m *DesiredStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateRequest.Marshal(b, m, deterministic)
}
func (m *DesiredStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateRequest.Merge(m, src)
}
func (m *DesiredStateRequest) XXX_Size() int {
	return xxx_messageInfo_DesiredStateRequest.Size(m)
}
func (m *DesiredStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateRequest proto.InternalMessageInfo

func (m *DesiredStateRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *DesiredStateRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

type Credentials struct {
	UserAccountName      string   `protobuf:"bytes,1,opt,name=userAccountName,proto3" json:"userAccountName,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Creds                string   `protobuf:"bytes,4,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUserAccountName() string {
	if m != nil {
		return m.UserAccountName
	}
	return ""
}

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credentials) GetCreds() string {
	if m != nil {
		return m.Creds
	}
	return ""
}

type DesiredStateResponse struct {
	Creds                []*Credentials `protobuf:"bytes,1,rep,name=creds,proto3" json:"creds,omitempty"`
	DeletedUsernames     []string       `protobuf:"bytes,2,rep,name=deletedUsernames,proto3" json:"deletedUsernames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DesiredStateResponse) Reset()         { *m = DesiredStateResponse{} }
func (m *DesiredStateResponse) String() string { return proto.CompactTextString(m) }
func (*DesiredStateResponse) ProtoMessage()    {}
func (*DesiredStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *DesiredStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateResponse.Unmarshal(m, b)
}
func (m *DesiredStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateResponse.Marshal(b, m, deterministic)
}
func (m *DesiredStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateResponse.Merge(m, src)
}
func (m *DesiredStateResponse) XXX_Size() int {
	return xxx_messageInfo_DesiredStateResponse.Size(m)
}
func (m *DesiredStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateResponse proto.InternalMessageInfo

func (m *DesiredStateResponse) GetCreds() []*Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *DesiredStateResponse) GetDeletedUsernames() []string {
	if m != nil {
		return m.DeletedUsernames
	}
	return nil
}

type DeleteAccountRequest struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DesiredStateRequest)(nil), "v1alpha1.DesiredStateRequest")
	proto.RegisterType((*Credentials)(nil), "v1alpha1.Credentials")
	proto.RegisterType((*DesiredStateResponse)(nil), "v1alpha1.DesiredStateResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "v1alpha1.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "v1alpha1.DeleteAccountResponse")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0xad, 0x4a, 0x3b, 0x49, 0x51, 0xd6, 0x16, 0x43, 0x40, 0x0d, 0x39, 0x05, 0x85, 0x40,
	0xeb, 0x45, 0xf0, 0xa4, 0xf5, 0xaa, 0x48, 0x82, 0x17, 0x6f, 0x6b, 0x76, 0xd4, 0x40, 0xcc, 0xc6,
	0xdd, 0x4d, 0xfd, 0x05, 0xfe, 0x1f, 0x7f, 0xa2, 0xe4, 0x4b, 0xf3, 0x61, 0xc1, 0xe3, 0xbc, 0xb7,
	0xf3, 0xe6, 0xbd, 0x99, 0x05, 0x33, 0x12, 0xe9, 0x73, 0xfc, 0xe2, 0x67, 0x52, 0x68, 0x41, 0xc7,
	0xeb, 0x05, 0x4b, 0xb2, 0x57, 0xb6, 0x70, 0x43, 0x38, 0xb8, 0x41, 0x15, 0x4b, 0xe4, 0xa1, 0x66,
	0x1a, 0x03, 0x7c, 0xcf, 0x51, 0x69, 0xea, 0x80, 0xc1, 0xa2, 0x48, 0xe4, 0xa9, 0xbe, 0x63, 0x6f,
	0x68, 0x11, 0x87, 0x78, 0x93, 0xa0, 0x0d, 0x51, 0x1b, 0xc6, 0xb9, 0x42, 0x99, 0x16, 0xf4, 0x96,
	0x33, 0xf2, 0x26, 0xc1, 0x4f, 0xed, 0x7e, 0x12, 0x30, 0x56, 0x12, 0x39, 0xa6, 0x3a, 0x66, 0x89,
	0xa2, 0x1e, 0xec, 0x15, 0xdc, 0xd5, 0x40, 0xb1, 0x0f, 0xf7, 0x54, 0x49, 0x5b, 0xb5, 0xe0, 0x32,
	0xa6, 0xd4, 0x87, 0x90, 0xdc, 0x1a, 0x55, 0x5c, 0x53, 0xd3, 0x19, 0xec, 0x44, 0x12, 0xb9, 0xb2,
	0xb6, 0x4b, 0xa2, 0x2a, 0x5c, 0x01, 0xb3, 0x6e, 0x38, 0x95, 0x89, 0x54, 0x21, 0x3d, 0x6b, 0x5e,
	0x13, 0x67, 0xe4, 0x19, 0xcb, 0xb9, 0xdf, 0xac, 0xc3, 0x6f, 0xb9, 0xae, 0x45, 0xe8, 0x29, 0xec,
	0x73, 0x4c, 0x50, 0x23, 0x7f, 0xa8, 0x9d, 0xa8, 0x3a, 0xf0, 0x00, 0x77, 0x2f, 0x8a, 0x81, 0x05,
	0x56, 0x67, 0xfa, 0xf7, 0x3a, 0xdd, 0x43, 0x98, 0xf7, 0x3a, 0x2b, 0xaf, 0xcb, 0x2f, 0x02, 0xd3,
	0x55, 0x79, 0xbb, 0x10, 0xe5, 0x3a, 0x8e, 0x90, 0xde, 0x82, 0xd9, 0x4e, 0x45, 0x8f, 0x7e, 0xed,
	0xff, 0x71, 0x4a, 0xfb, 0x78, 0x13, 0x5d, 0x2f, 0xe3, 0x1e, 0xa6, 0x9d, 0xc9, 0xb4, 0xd3, 0x30,
	0x0c, 0x63, 0x9f, 0x6c, 0xe4, 0x2b, 0xc5, 0x6b, 0xf3, 0x11, 0xfc, 0xcb, 0xe6, 0xcd, 0xd3, 0x6e,
	0xf9, 0xe5, 0xce, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x18, 0x3e, 0x28, 0xd0, 0x82, 0x02, 0x00,
	0x00,
}
