exclude: "(?x)^(.*/base/charts/.*)"
repos:
  # general stuff
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Git style
      - id: check-added-large-files
        exclude: ^vendor/
      - id: check-merge-conflict
        exclude: ^vendor/
      - id: check-vcs-permalinks
        exclude: ^vendor/
      - id: forbid-new-submodules
        exclude: ^vendor/
      - id: no-commit-to-branch
        exclude: ^vendor/

      # Common errors
      - id: end-of-file-fixer
        exclude: ^vendor/
      - id: trailing-whitespace
        exclude: ^vendor/
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        exclude: ^vendor/
      - id: check-merge-conflict
        exclude: ^vendor/
      - id: check-executables-have-shebangs
        exclude: ^vendor/

  # markdown
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: master
    hooks:
      - id: markdownlint_docker
        exclude: ^vendor/
