apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anck-credentials
  labels:
    k8s-app: anck-credentials
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
