// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DesiredStateRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Username             []string `protobuf:"bytes,2,rep,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesiredStateRequest) Reset()         { *m = DesiredStateRequest{} }
func (m *DesiredStateRequest) String() string { return proto.CompactTextString(m) }
func (*DesiredStateRequest) ProtoMessage()    {}
func (*DesiredStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DesiredStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateRequest.Unmarshal(m, b)
}
func (m *DesiredStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateRequest.Marshal(b, m, deterministic)
}
func (m *DesiredStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateRequest.Merge(m, src)
}
func (m *DesiredStateRequest) XXX_Size() int {
	return xxx_messageInfo_DesiredStateRequest.Size(m)
}
func (m *DesiredStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateRequest proto.InternalMessageInfo

func (m *DesiredStateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *DesiredStateRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

type DesiredStateResponse struct {
	Credentials          map[string]string `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DesiredStateResponse) Reset()         { *m = DesiredStateResponse{} }
func (m *DesiredStateResponse) String() string { return proto.CompactTextString(m) }
func (*DesiredStateResponse) ProtoMessage()    {}
func (*DesiredStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *DesiredStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesiredStateResponse.Unmarshal(m, b)
}
func (m *DesiredStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesiredStateResponse.Marshal(b, m, deterministic)
}
func (m *DesiredStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesiredStateResponse.Merge(m, src)
}
func (m *DesiredStateResponse) XXX_Size() int {
	return xxx_messageInfo_DesiredStateResponse.Size(m)
}
func (m *DesiredStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DesiredStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DesiredStateResponse proto.InternalMessageInfo

func (m *DesiredStateResponse) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *DesiredStateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type DeleteAccountResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*DesiredStateRequest)(nil), "v1alpha1.DesiredStateRequest")
	proto.RegisterType((*DesiredStateResponse)(nil), "v1alpha1.DesiredStateResponse")
	proto.RegisterMapType((map[string]string)(nil), "v1alpha1.DesiredStateResponse.CredentialsEntry")
	proto.RegisterType((*DeleteAccountRequest)(nil), "v1alpha1.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "v1alpha1.DeleteAccountResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x45, 0x99, 0x04, 0xb5, 0x79, 0xb5, 0x50, 0xc6, 0x0a, 0x21, 0xa0, 0x86, 0xac, 0xb2, 0x31,
	0xda, 0xba, 0x11, 0x17, 0x82, 0x54, 0x57, 0x22, 0x68, 0xfa, 0x05, 0x63, 0xfa, 0xd4, 0xc1, 0x38,
	0x13, 0x67, 0x26, 0x81, 0xfe, 0x95, 0x7f, 0xe0, 0xaf, 0x49, 0x92, 0xa6, 0x26, 0xd5, 0xea, 0x2e,
	0x97, 0x70, 0x1e, 0xf7, 0x5c, 0x06, 0x1c, 0x96, 0xf1, 0x28, 0x53, 0xd2, 0x48, 0xda, 0x2b, 0xc6,
	0x2c, 0xcd, 0x5e, 0xd8, 0x38, 0xb8, 0x85, 0xbd, 0x6b, 0xd4, 0x5c, 0xe1, 0x7c, 0x66, 0x98, 0xc1,
	0x18, 0xdf, 0x73, 0xd4, 0x86, 0xba, 0xb0, 0xc3, 0x92, 0x44, 0xe6, 0xc2, 0xb8, 0xc4, 0x27, 0xa1,
	0x13, 0x37, 0x91, 0x7a, 0xd0, 0xcb, 0x35, 0x2a, 0xc1, 0xde, 0xd0, 0xb5, 0x7c, 0x3b, 0x74, 0xe2,
	0x55, 0x0e, 0x3e, 0x09, 0x8c, 0xba, 0xd7, 0x74, 0x26, 0x85, 0x46, 0xfa, 0x00, 0xfd, 0x44, 0xe1,
	0x1c, 0x85, 0xe1, 0x2c, 0xd5, 0x2e, 0xf1, 0xed, 0xb0, 0x3f, 0x39, 0x89, 0x9a, 0x16, 0xd1, 0x6f,
	0x50, 0x34, 0xfd, 0x26, 0x6e, 0x84, 0x51, 0x8b, 0xb8, 0x7d, 0x83, 0x8e, 0x60, 0x0b, 0x95, 0x92,
	0xca, 0xb5, 0xaa, 0x7e, 0x75, 0xf0, 0x2e, 0x61, 0xb8, 0x8e, 0xd1, 0x21, 0xd8, 0xaf, 0xb8, 0x58,
	0x7a, 0x94, 0x9f, 0x25, 0x5b, 0xb0, 0x34, 0xc7, 0x86, 0xad, 0xc2, 0x85, 0x75, 0x4e, 0x82, 0xd3,
	0x52, 0x20, 0x45, 0x83, 0x57, 0xb5, 0xee, 0xbf, 0x7b, 0x04, 0xc7, 0xb0, 0xbf, 0x46, 0x2c, 0x9d,
	0x57, 0x05, 0x49, 0xab, 0xe0, 0xe4, 0x83, 0xc0, 0x60, 0x2a, 0xc5, 0x13, 0x7f, 0x9e, 0xa1, 0x2a,
	0x78, 0x82, 0xf4, 0x0e, 0x76, 0xdb, 0xfa, 0xf4, 0x60, 0xd3, 0x2c, 0x55, 0x13, 0xef, 0xf0, 0xef,
	0xd5, 0xe8, 0x3d, 0x0c, 0x3a, 0x7d, 0x68, 0x07, 0xf8, 0xa9, 0xe6, 0x1d, 0x6d, 0xfc, 0x5f, 0x5f,
	0x7c, 0xdc, 0xae, 0xde, 0xcc, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x5c, 0xc1, 0x09,
	0x40, 0x02, 0x00, 0x00,
}
