# yaml-language-server: https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nats
  namespace: default
  version: v0.9.0
  repo: https://nats-io.github.io/k8s/helm/charts/
  releaseName: global
  valuesInline:
    nats:
      jetstream:
        enabled: true
        memStorage:
          enabled: true
          size: 2Gi
        fileStorage:
          enabled: true
          size: "10Gi"
          storageDirectory: /data/
          storageClassName: default
      cluster:
        enabled: true
        replicas: 3
    leadnode:
      enabled: false
    natsbox:
      enabled: false

