apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  volumeClaimTemplates:
  - metadata:
      name: nats-js-pvc
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
      storageClassName: "local-path"
